# Generated by Django 2.2.9 on 2020-07-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200522_1109'),
        ('openebs', '0008_auto_20200522_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv15stopmessage',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kv1.Kv1Line', verbose_name='lijn'),
        ),
        migrations.AlterUniqueTogether(
            name='kv15stopmessage',
            unique_together={('dataownercode', 'messagecodedate', 'messagecodenumber', 'line')},
        ),
    ]
