# Generated by Django 2.2.9 on 2020-02-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200122_1655'),
        ('openebs', '0008_auto_20200122_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kv17ChangeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataownercode', models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI')], max_length=10, verbose_name='Vervoerder')),
                ('operatingday', models.DateField(verbose_name='Datum')),
                ('is_cancel', models.BooleanField(default=True, help_text='Rit kan ook een toelichting zijn voor een halte', verbose_name='Opgeheven?')),
                ('is_recovered', models.BooleanField(default=False, verbose_name='Teruggedraaid?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recovered', models.DateTimeField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kv1.Kv1Line', verbose_name='Lijn')),
            ],
            options={
                'verbose_name': 'Lijnaanpassing',
                'verbose_name_plural': 'Lijnaanpassingen',
                'permissions': (('view_change', 'Ritaanpassingen bekijken'), ('add_change', 'Ritaanpassingen aanmaken')),
                'unique_together': {('operatingday', 'line')},
            },
        ),
        migrations.DeleteModel(
            name='Kv17ChangeAll',
        ),
    ]
