# Generated by Django 2.2.9 on 2020-04-22 13:12

from django.db import migrations, models
import django.db.models.deletion
import openebs.models


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200416_1851'),
        ('openebs', '0008_auto_20200417_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv17journeychange',
            name='monitoring_error',
            field=models.CharField(blank=True, choices=[('GPS', 'Storing in de GPS van het voertuig'), ('GPRS', 'Storing in het mobiele netwerk'), ('Radio', 'Storing in de radioverbinding'), ('General', 'Voertuigsysteem werkt niet'), ('NoSystem', 'Voertuig heeft geen volgapparatuur'), ('other', 'Andere oorzaak'), ('unknown', 'Onbekende oorzaak')], max_length=40, verbose_name='Monitoring_error'),
        )

    ]
