# Generated by Django 2.2.9 on 2020-02-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0009_auto_20200204_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataowner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Dataowners',
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('dataowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openebs.Dataowner')),
            ],
        ),
    ]
