# Generated by Django 2.2.9 on 2020-02-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0010_dataowner_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lines',
            name='dataowner',
        ),
        migrations.DeleteModel(
            name='Dataowner',
        ),
        migrations.DeleteModel(
            name='Lines',
        ),
    ]
