# Generated by Django 2.2.9 on 2020-06-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200522_1109'),
        ('openebs', '0011_kv17change_monitoring_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kv17change',
            options={'permissions': (('view_change', 'Ritaanpassingen bekijken'), ('add_change', 'Ritaanpassingen aanmaken'), ('cancel_lines', 'Lijnen annuleren'), ('cancel_alllines', 'Vervoerder annuleren'), ('view_shorten', 'Ritverkortingen bekijken'), ('add_shorten', 'Ritverkortingen aanmaken')), 'verbose_name': 'Ritaanpassing', 'verbose_name_plural': 'Ritaanpassingen'},
        ),
        migrations.AddField(
            model_name='kv17change',
            name='is_shorten',
            field=models.BooleanField(default=False, verbose_name='Ingekort?'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kv1.Kv1Stop'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='stoporder',
            field=models.IntegerField(null=True),
        ),
    ]
