# Generated by Django 2.2.9 on 2020-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0011_auto_20200205_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
