# Generated by Django 2.2.9 on 2020-02-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0012_dates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates',
        ),
    ]
